{{- if .Values.minAvailable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Chart.Name }}-pdb
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
{{- end }}